version: '3.9'
services:
  api:
    build: .
    container_name: api
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: ufc_stats_api
    volumes:
      - './:/src'
  db:
    image: postgres:16.0
    container_name: db
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ufc_stats_api
    volumes:
      - ./sql/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
